name: ci # started testing SFTP Deploy Action

on:
  push:
    branches:
      - main

jobs:
  Upload-to-SFTP:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code # Checkout the latest code
        uses: actions/checkout@v3

      - name: SFTP uploader # Upload to SFTP
        uses: wangyucode/sftp-upload-action@v2.0.4
        with:
          host: ${{ secrets.SFTP_HOST }} # Recommended to put the credentials in github secrets.
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          # compress: true # Compression
          forceUpload: true # Optional, Force uploading all files, Default to false(upload only newer files).
          localDir: "./docs/tags.md" # Required, Absolute or relative to cwd.
          remoteDir: "/" # Required, Absolute path only.
          # exclude: ".git,.DS_Store,**/node_modules" # Optional. exclude patterns (glob) like .gitignore, use ',' to split, Default to ''.
